#!/bin/bash
#
# Copyright 2011 TouK
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Author: msk@touk.pl
# This script expects one parameter - a file produced by extract_hades_logs.sh. For the given file gnuplot script is printed.

function usage {
    echo "Usage: $(basename $0) <file generated by extract_hades_logs.sh>" >&2
    exit 1
}

if [ $# -ne 1 ]; then usage; fi

MAX_Y=10

echo "set yrange [0:$MAX_Y]"
echo "plot \"$1\" using 1:2 title \"main\", \"$1\" using 1:4 title \"failover\""
